# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_origin', models.CharField(choices=[('C', '设备类型'), ('D', '设备')], help_text='设备源类型', max_length=20, verbose_name='设备源类型')),
                ('name', models.CharField(blank=True, help_text='规则名称', max_length=50, null=True, verbose_name='规则名称')),
                ('desc', models.TextField(blank=True, help_text='规则描述', null=True, verbose_name='规则描述')),
                ('rule_type', models.CharField(choices=[('AUP', '属性上报预处理'), ('AU', '属性上报'), ('ADP', '属性下发预处理'), ('AD', '属性下发'), ('EU', '事件上报'), ('DU', '自定义上报')], help_text='规则类型', max_length=50, verbose_name='规则类型')),
                ('condition', models.JSONField(blank=True, help_text='属性条件配置', null=True, verbose_name='属性条件配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('event_identifier', models.CharField(blank=True, help_text='规则类型为EU(事件上报)时，必传', max_length=50, null=True, verbose_name='事件标识符')),
                ('data_stream_identifier', models.CharField(blank=True, help_text='规则类型为DU(自定义上报）时，必传', max_length=50, null=True, verbose_name='数据流标识符')),
                ('is_record', models.BooleanField(default=False, help_text='规则 调试状态', verbose_name='规则 调试状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_rules', to='equipments.devicecategory', verbose_name='设备类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_rules', to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则',
            },
        ),
        migrations.CreateModel(
            name='RuleActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='操作类型', max_length=100, verbose_name='操作类型')),
                ('exec_conf', models.JSONField(blank=True, help_text='操作配置', null=True, verbose_name='操作配置')),
                ('order', models.IntegerField(default=1, help_text='序号', verbose_name='序号')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rules.rules', verbose_name='规则')),
            ],
            options={
                'verbose_name': '规则操作',
                'verbose_name_plural': '规则操作',
            },
        ),
        migrations.CreateModel(
            name='DeviceRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allow', models.BooleanField(default=True, verbose_name='是否允许设备使用')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_rules', to='equipments.device', verbose_name='设备')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_devices', to='rules.rules', verbose_name='规则')),
            ],
            options={
                'verbose_name': '任务设备',
                'verbose_name_plural': '任务设备',
            },
        ),
    ]
