# Generated by Django 4.2.20 on 2025-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rules_device_category_alter_rules_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='rule_type',
            field=models.CharField(choices=[('AUP', '属性上报预处理'), ('AU', '属性上报'), ('ADP', '属性下发预处理'), ('AD', '属性下发'), ('EU', '事件上报'), ('DU', '自定义上报'), ('SAUP', '上报子设备属性预处理')], help_text='规则类型', max_length=50, verbose_name='规则类型'),
        ),
    ]
