# Generated by Django 4.2.20 on 2025-08-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_rules_rule_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicerules',
            options={'verbose_name': '规则-设备级', 'verbose_name_plural': '规则-设备级'},
        ),
    ]
