# Generated by Django 4.2.17 on 2024-12-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_projects_bucket_disk_usage_and_more"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.projects",
            ),
        ),
    ]
