# Generated by Django 4.2.20 on 2026-02-26 09:22

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_max_project_count'),
        ('custom_reqlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customrequestlogs',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddField(
            model_name='customrequestlogs',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.projects', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='customrequestlogs',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='请求体'),
        ),
        migrations.AlterField(
            model_name='customrequestlogs',
            name='full_path',
            field=models.TextField(blank=True, null=True, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='customrequestlogs',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端ip'),
        ),
        migrations.AlterField(
            model_name='customrequestlogs',
            name='query_params',
            field=models.TextField(blank=True, null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='customrequestlogs',
            name='res_data',
            field=models.TextField(blank=True, null=True, verbose_name='返回数据'),
        ),
    ]
