# Generated by Django 4.2.20 on 2025-09-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0054_alter_devicecategory_access_protocol'),
        ('users', '0014_alter_projectmembers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzvizConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('china', '中国大陆'), ('singapore', '新加坡'), ('india', '印度'), ('europe', '欧洲'), ('america', '美洲'), ('south_america', '南美洲')], help_text='萤石云服务区域', max_length=20, verbose_name='区域')),
                ('app_key', models.CharField(help_text='萤石云应用Key', max_length=32, verbose_name='AppKey')),
                ('secret', models.CharField(help_text='萤石云应用密钥', max_length=32, verbose_name='Secret')),
                ('is_configured', models.BooleanField(default=False, help_text='是否已配置', verbose_name='是否已配置')),
                ('last_test_time', models.DateTimeField(blank=True, help_text='最后测试连接时间', null=True, verbose_name='最后测试时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('project', models.OneToOneField(help_text='项目', on_delete=django.db.models.deletion.CASCADE, to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '萤石云配置',
                'verbose_name_plural': '萤石云配置',
            },
        ),
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(help_text='设备序列号', max_length=32, unique=True, verbose_name='设备序列号')),
                ('device_name', models.CharField(help_text='设备名称', max_length=100, verbose_name='设备名称')),
                ('pic_url', models.URLField(blank=True, help_text='设备图片URL', verbose_name='设备图片')),
                ('status', models.IntegerField(default=1, help_text='设备状态', verbose_name='设备状态')),
                ('is_online', models.BooleanField(default=False, help_text='是否在线', verbose_name='是否在线')),
                ('channel_no', models.IntegerField(default=1, help_text='通道号', verbose_name='通道号')),
                ('device_type', models.CharField(choices=[('IPC', '网络摄像头'), ('NVR', '网络录像机'), ('DVR', '硬盘录像机')], default='IPC', help_text='设备类型', max_length=20, verbose_name='设备类型')),
                ('add_time', models.DateTimeField(help_text='设备添加时间', verbose_name='添加时间')),
                ('last_online_time', models.DateTimeField(blank=True, help_text='最后在线时间', null=True, verbose_name='最后在线时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('linked_device', models.ForeignKey(blank=True, help_text='关联的设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.device', verbose_name='关联设备')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '摄像头设备',
                'verbose_name_plural': '摄像头设备',
            },
        ),
        migrations.CreateModel(
            name='CameraAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.CharField(help_text='告警ID', max_length=100, unique=True, verbose_name='告警ID')),
                ('channel', models.IntegerField(help_text='通道', verbose_name='通道')),
                ('channel_type', models.IntegerField(help_text='通道类型', verbose_name='通道类型')),
                ('alarm_type', models.CharField(help_text='告警类型', max_length=50, verbose_name='告警类型')),
                ('relation_id', models.CharField(blank=True, help_text='关联ID', max_length=100, verbose_name='关联ID')),
                ('location', models.CharField(blank=True, help_text='位置', max_length=200, verbose_name='位置')),
                ('describe', models.TextField(blank=True, help_text='描述', verbose_name='描述')),
                ('alarm_time', models.DateTimeField(help_text='告警时间', verbose_name='告警时间')),
                ('custom_type', models.CharField(blank=True, help_text='自定义类型', max_length=100, verbose_name='自定义类型')),
                ('request_time', models.BigIntegerField(help_text='请求时间戳', verbose_name='请求时间')),
                ('channel_name', models.CharField(blank=True, help_text='通道名称', max_length=100, verbose_name='通道名称')),
                ('checksum', models.CharField(blank=True, help_text='校验和', max_length=200, verbose_name='校验和')),
                ('crypt', models.IntegerField(default=0, help_text='加密标识', verbose_name='加密')),
                ('custom_info', models.TextField(blank=True, help_text='自定义信息', verbose_name='自定义信息')),
                ('intelligent_data', models.TextField(blank=True, help_text='智能数据', verbose_name='智能数据')),
                ('picture_list', models.JSONField(default=list, help_text='图片列表', verbose_name='图片列表')),
                ('short_url', models.URLField(blank=True, help_text='短链接', verbose_name='短链接')),
                ('url', models.URLField(blank=True, help_text='链接', verbose_name='链接')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, to='camera.cameradevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': '摄像头告警记录',
                'verbose_name_plural': '摄像头告警记录',
                'ordering': ['-alarm_time'],
            },
        ),
    ]
