# Generated by Django 4.2.20 on 2025-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraalarm',
            name='device',
        ),
        migrations.AddField(
            model_name='cameraalarm',
            name='device_serial',
            field=models.CharField(default='GC4285371', help_text='设备序列号', max_length=32, verbose_name='设备序列号'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CameraDevice',
        ),
    ]
