# Generated by Django 4.2.20 on 2025-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_remove_cameraalarm_device_cameraalarm_device_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraalarm',
            name='intelligent_data',
        ),
        migrations.RemoveField(
            model_name='cameraalarm',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='cameraalarm',
            name='url',
        ),
    ]
