# Generated by Django 4.2.20 on 2025-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_remove_cameraalarm_intelligent_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezvizconfig',
            name='product_code',
            field=models.CharField(default='ezviz.camera.common.4', help_text='萤石云摄像头产品识别码', max_length=50, verbose_name='产品识别码'),
            preserve_default=False,
        ),
    ]
