# Generated by Django 4.2.20 on 2025-10-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_ezvizconfig_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezvizconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='用于验证Webhook回调的签名密钥', max_length=64, verbose_name='Webhook签名密钥'),
        ),
    ]
