# Generated by Django 4.2.20 on 2025-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_ezvizconfig_webhook_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraalarm',
            options={'ordering': ['-alarm_time'], 'verbose_name': '视频通道告警记录', 'verbose_name_plural': '视频通道告警记录'},
        ),
        migrations.AlterField(
            model_name='ezvizconfig',
            name='region',
            field=models.CharField(choices=[('china', '中国大陆'), ('europe', '欧洲'), ('north_america', '北美'), ('south_america', '南美'), ('singapore', '新加坡'), ('india', '印度'), ('russia', '俄罗斯')], help_text='萤石云服务区域', max_length=20, verbose_name='区域'),
        ),
    ]
