# Generated by Django 4.2.20 on 2025-10-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_alter_cameraalarm_options_alter_ezvizconfig_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ezvizconfig',
            name='is_configured',
        ),
    ]
