# Generated by Django 4.2.20 on 2025-10-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_projectmembers_options'),
        ('camera', '0007_remove_ezvizconfig_is_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraalarm',
            name='project',
            field=models.ForeignKey(default='PR_TchL4usnan', help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='users.projects', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
