# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(blank=True, help_text='设备名称', max_length=30, null=True, verbose_name='设备名称')),
                ('cfg_info', models.JSONField(blank=True, help_text='设备配置参数', null=True, verbose_name='设备配置参数')),
                ('exclude_attrs', models.JSONField(blank=True, help_text='设备排除属性', null=True, verbose_name='设备排除属性')),
                ('logo', models.TextField(blank=True, help_text='设备logo', null=True, verbose_name='设备logo')),
                ('location', models.CharField(blank=True, help_text='设备安裝位置', max_length=100, null=True, verbose_name='设备安裝位置')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('unit_order', models.IntegerField(default=1, help_text='单元内序号', verbose_name='单元内序号')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='设备连接名称')),
                ('password', models.CharField(max_length=50, verbose_name='设备连接密码')),
                ('client_id', models.CharField(max_length=100, verbose_name='设备连接client_id')),
                ('code', models.CharField(blank=True, help_text='子设备标识符', max_length=50, null=True, verbose_name='子设备标识符')),
                ('desc', models.TextField(blank=True, help_text='设备描述', null=True, verbose_name='设备描述')),
                ('is_record', models.BooleanField(default=False, help_text='设备调试消息日志按钮', verbose_name='设备调试消息日志按钮')),
                ('belong_unit', models.ForeignKey(blank=True, help_text='所属单元', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_devices', to='users.devicegroups', verbose_name='所属单元')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='设备类型名称', max_length=100, null=True, verbose_name='设备类型名称')),
                ('desc', models.TextField(blank=True, help_text='设备类型描述', null=True, verbose_name='设备类型描述')),
                ('quote_product', models.CharField(choices=[('P', '产品类型'), ('C', '自定义类型'), ('S', '标准类型')], default='S', help_text='类型分类', max_length=20, verbose_name='类型分类')),
                ('node_type', models.CharField(choices=[('DD', '直连设备'), ('CG', '网关'), ('SD', '子设备')], help_text='设备接入类型', max_length=20, verbose_name='设备接入类型')),
                ('access_protocol', models.CharField(blank=True, choices=[('SP', 'EasyCloud标准协议'), ('SGP', 'EasyCloud标准网关协议'), ('MRP', 'ModBus RTU透传协议'), ('MGRP', 'ModBus RTU云网关协议'), ('OTHER', '其它')], help_text='设备接入协议', max_length=30, null=True, verbose_name='设备接入协议')),
                ('net_type', models.CharField(blank=True, choices=[('wifi', 'WiFi'), ('ethernet', '以太网'), ('cellular', '蜂窝网络（4G/5G）'), ('nbiot', 'NB-IoT'), ('other', '其它')], help_text='设备通信方式', max_length=50, null=True, verbose_name='设备通信方式')),
                ('cfg_info', models.JSONField(blank=True, help_text='配置信息', null=True, verbose_name='配置信息')),
                ('other_info', models.JSONField(blank=True, help_text='扩展信息', null=True, verbose_name='扩展信息')),
                ('scene_action', models.BooleanField(default=False, help_text='是否参与场景动作', verbose_name='是否参与场景动作')),
                ('scene_condition', models.BooleanField(default=False, help_text='是否参与场景条件', verbose_name='是否参与场景条件')),
                ('online_delay_time', models.IntegerField(default=300, help_text='设备在线延迟时间', verbose_name='设备在线延迟时间')),
                ('alive_delay_time', models.IntegerField(default=300, help_text='设备活跃延迟时间', verbose_name='设备活跃延迟时间')),
                ('logo', models.TextField(blank=True, help_text='设备类型logo', null=True, verbose_name='设备类型logo')),
                ('fixed_product', models.CharField(blank=True, help_text='当产品类型quote_product为产品类型（P）时，必传', max_length=20, null=True, verbose_name='产品类型标识')),
                ('down_interval', models.IntegerField(blank=True, default=2000, help_text='下发间隔', null=True, verbose_name='下发间隔')),
                ('communication_waiting_time', models.IntegerField(blank=True, default=3000, help_text='通讯等待时间', null=True, verbose_name='通讯等待时间')),
                ('timout_retry_count', models.PositiveIntegerField(blank=True, default=2, help_text='超时重发次数', null=True, verbose_name='超时重发次数')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_device_category', to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategoryDataStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='数据流名称', max_length=100, null=True, verbose_name='数据流名称')),
                ('desc', models.TextField(blank=True, help_text='数据流描述', null=True, verbose_name='数据流描述')),
                ('key', models.CharField(help_text='数据流标识符', max_length=100, verbose_name='数据流标识符')),
                ('data_type', models.CharField(choices=[('M', 'ModBus RTU'), ('J', 'JSON'), ('H', 'HEX'), ('P', 'PlainText')], help_text='消息格式', max_length=20, verbose_name='消息格式')),
                ('topic_mode', models.BooleanField(default=False, help_text='是否支持自定义topic', verbose_name='是否支持自定义topic')),
                ('publish_topic', models.CharField(blank=True, help_text='发布 Topic', max_length=100, null=True, verbose_name='发布 Topic')),
                ('subscribe_topic', models.CharField(blank=True, help_text='订阅 Topic', max_length=100, null=True, verbose_name='订阅 Topic')),
                ('publish_topic_key', models.CharField(blank=True, help_text='高级模式发布Topic key', max_length=100, null=True, verbose_name='高级模式发布Topic key')),
                ('subscribe_topic_key', models.CharField(blank=True, help_text='订阅 高级模式订阅Topic key', max_length=100, null=True, verbose_name='高级模式订阅Topic key')),
                ('bind_tcp', models.BooleanField(default=False, help_text='绑定tcp', verbose_name='绑定tcp')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='data_streams', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '自定义数据流',
                'verbose_name_plural': '自定义数据流',
                'unique_together': {('device_category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MQTTBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_address', models.CharField(max_length=100)),
                ('broker_port', models.CharField(max_length=20)),
                ('broker_port_tls', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '设备-MQTT连接信息',
                'verbose_name_plural': '设备-MQTT连接信息',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(blank=True, help_text='名称', max_length=100, null=True, verbose_name='名称')),
                ('product_key', models.CharField(help_text='产品唯一标识productKey', max_length=100, unique=True, verbose_name='productKey')),
                ('description', models.TextField(blank=True, help_text='产品描述', null=True, verbose_name='产品描述')),
                ('node_type', models.CharField(choices=[('DD', '直连设备'), ('CG', '网关'), ('SD', '子设备')], help_text='节点类型', max_length=20, verbose_name='节点类型')),
                ('model', models.CharField(blank=True, help_text='产品型号', max_length=100, null=True, verbose_name='产品型号')),
                ('category', models.CharField(blank=True, help_text='产品类别', max_length=100, null=True, verbose_name='产品类别')),
                ('series', models.CharField(blank=True, help_text='产品系列', max_length=100, null=True, verbose_name='产品系列')),
                ('gateway_type', models.CharField(blank=True, choices=[('LoRaWAN', '星纵网关'), ('IoT', '云垦网关')], help_text='网关类型', max_length=100, null=True, verbose_name='网关类型')),
                ('logo', models.TextField(blank=True, help_text='产品logo', null=True, verbose_name='产品logo')),
                ('cfg_info', models.JSONField(blank=True, help_text='产品配置信息', null=True, verbose_name='产品配置信息')),
                ('scene_action', models.BooleanField(default=False, help_text='是否参与场景动作', verbose_name='是否参与场景动作')),
                ('scene_condition', models.BooleanField(default=False, help_text='是否参与场景条件', verbose_name='是否参与场景条件')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='OperatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='操作描述', null=True, verbose_name='操作描述')),
                ('result', models.CharField(blank=True, help_text='执行结果', max_length=100, null=True, verbose_name='执行结果')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, to='equipments.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备操作记录',
                'verbose_name_plural': '设备操作记录',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='厂商名称', max_length=60, unique=True, verbose_name='厂商名称')),
                ('remark', models.TextField(blank=True, help_text='备注说明', null=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '厂商信息',
                'verbose_name_plural': '厂商信息',
            },
        ),
        migrations.CreateModel(
            name='FixedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_string', models.CharField(max_length=20, unique=True, verbose_name='确定产品标识符')),
                ('name', models.CharField(blank=True, help_text='产品名称', max_length=60, null=True, verbose_name='产品名称')),
                ('model', models.CharField(blank=True, help_text='产品型号', max_length=50, null=True, verbose_name='产品型号')),
                ('version', models.CharField(blank=True, help_text='版本号', max_length=20, null=True, verbose_name='版本号')),
                ('trade_name', models.CharField(blank=True, help_text='厂商名称', max_length=20, null=True, verbose_name='厂商名称')),
                ('conf', models.JSONField(help_text='设备类型相关的全量配置信息', verbose_name='设备类型相关的全量配置信息')),
                ('remark', models.TextField(blank=True, help_text='备注说明', null=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '固定产品类型',
                'verbose_name_plural': '固定产品类型',
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(help_text='当前状态', verbose_name='当前状态')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='时间', verbose_name='时间戳')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, to='equipments.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备状态变化表',
                'verbose_name_plural': '设备状态变化表',
            },
        ),
        migrations.CreateModel(
            name='DeviceCommandRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='命令名称', max_length=100, verbose_name='命令名称')),
                ('key', models.CharField(help_text='命令标识符', max_length=100, verbose_name='命令标识符')),
                ('request_time', models.DateTimeField(blank=True, help_text='命令下发时间', null=True, verbose_name='命令下发时间')),
                ('request_content', models.TextField(blank=True, help_text='命令下发内容', null=True, verbose_name='命令下发内容')),
                ('response_time', models.DateTimeField(blank=True, help_text='命令回复时间', null=True, verbose_name='命令回复时间')),
                ('response_content', models.TextField(blank=True, help_text='命令回复内容', null=True, verbose_name='命令回复内容')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, related_name='command_records', to='equipments.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备命令记录',
                'verbose_name_plural': '设备命令记录',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategoryModBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_publish_type', models.CharField(blank=True, help_text='下发推送方式', max_length=20, null=True, verbose_name='下发推送方式')),
                ('it_switch', models.BooleanField(default=True, help_text='智能属性切换', verbose_name='智能属性切换')),
                ('io_register', models.JSONField(blank=True, help_text='io 寄存器设置', null=True, verbose_name='io 寄存器设置')),
                ('data_register', models.JSONField(blank=True, help_text='数据寄存器设置', null=True, verbose_name='数据寄存器设置')),
                ('data_stream', models.ForeignKey(blank=True, help_text='自定义数据流', null=True, on_delete=django.db.models.deletion.PROTECT, to='equipments.devicecategorydatastream', verbose_name='自定义数据流')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='mod_bus_conf', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': 'ModBus 配置',
                'verbose_name_plural': 'ModBus 配置',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, help_text='设备类型', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_devices', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='com_gateway',
            field=models.ForeignKey(blank=True, help_text='所属网关', null=True, on_delete=django.db.models.deletion.PROTECT, to='equipments.device', verbose_name='所属网关'),
        ),
        migrations.AddField(
            model_name='device',
            name='conn_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipments.mqttbroker', verbose_name='mqtt连接地址-端口'),
        ),
        migrations.AddField(
            model_name='device',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='device',
            name='members',
            field=models.ManyToManyField(related_name='member_devices', to='users.projectmembers', verbose_name='设备用户'),
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.PROTECT, related_name='project_device', to='users.projects', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='DeviceCategoryEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='事件名称', max_length=100, null=True, verbose_name='事件名称')),
                ('desc', models.TextField(blank=True, help_text='事件描述', null=True, verbose_name='事件描述')),
                ('key', models.CharField(help_text='事件标识符', max_length=100, verbose_name='事件标识符')),
                ('params', models.JSONField(blank=True, help_text='事件参数', null=True, verbose_name='事件参数')),
                ('order', models.IntegerField(default=1, help_text='序号', verbose_name='序号')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备类型-事件',
                'verbose_name_plural': '设备类型-事件',
                'unique_together': {('device_category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DeviceCategoryCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='命令名称', max_length=100, null=True, verbose_name='命令名称')),
                ('desc', models.TextField(blank=True, help_text='命令描述', null=True, verbose_name='命令描述')),
                ('key', models.CharField(help_text='命令标识符', max_length=100, verbose_name='命令标识符')),
                ('request_params', models.JSONField(blank=True, help_text='命令参数', null=True, verbose_name='命令参数')),
                ('response_params', models.JSONField(blank=True, help_text='命令回复参数', null=True, verbose_name='命令回复参数')),
                ('order', models.IntegerField(default=1, help_text='序号', verbose_name='序号')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备类型-命令',
                'verbose_name_plural': '设备类型-命令',
                'unique_together': {('device_category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DeviceCategoryAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='属性名称', max_length=100, null=True, verbose_name='属性名称')),
                ('desc', models.TextField(blank=True, help_text='属性描述', null=True, verbose_name='属性描述')),
                ('key', models.CharField(help_text='属性标识符', max_length=100, verbose_name='属性标识符')),
                ('attr_type', models.CharField(blank=True, choices=[('U', '设备上报'), ('D', '云端下发'), ('CS', '双向传输'), ('CP', '云端私有')], help_text='属性类型', max_length=50, null=True, verbose_name='属性类型')),
                ('data_type', models.CharField(choices=[('N', '数值(Number)'), ('B', '开关量(Boolean)'), ('T', '文本(String)'), ('E', '枚举(Enum)'), ('O', '键值对(Object)'), ('L', '列表(List)')], help_text='属性数据类型', max_length=20, verbose_name='属性数据类型')),
                ('is_required', models.BooleanField(default=False, help_text='设备可否弃用该属性', verbose_name='是否必要')),
                ('condition_info', models.JSONField(blank=True, help_text='属性计算配置', null=True, verbose_name='属性计算配置')),
                ('data_specs', models.JSONField(blank=True, help_text='属性约束', null=True, verbose_name='属性约束')),
                ('order', models.IntegerField(default=1, help_text='序号', verbose_name='序号')),
                ('is_scene', models.BooleanField(default=True, help_text='是否参与场景配置', verbose_name='是否参与场景配置')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='attrs', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备类型-属性',
                'verbose_name_plural': '设备类型-属性',
                'unique_together': {('device_category', 'key')},
            },
        ),
    ]
