# Generated by Django 4.2.10 on 2024-02-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_projects_name'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, help_text='设备类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_devices', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='com_gateway',
            field=models.ForeignKey(blank=True, help_text='所属网关', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.device', verbose_name='所属网关'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='尚未命名', help_text='设备名称', max_length=30, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_device', to='users.projects', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_device_category', to='users.projects', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='devicecategoryattrs',
            name='device_category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devicecategorydatastream',
            name='device_category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='data_streams', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devicecategorymodbus',
            name='data_stream',
            field=models.ForeignKey(blank=True, help_text='自定义数据流', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.devicecategorydatastream', verbose_name='自定义数据流'),
        ),
        migrations.AlterField(
            model_name='devicecategorymodbus',
            name='device_category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='mod_bus_conf', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
    ]
