# Generated by Django 4.2.10 on 2024-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_device_category_alter_device_com_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='communication_waiting_time',
            field=models.IntegerField(blank=True, default=2000, help_text='通讯等待时间', null=True, verbose_name='通讯等待时间'),
        ),
    ]
