# Generated by Django 4.2.10 on 2024-02-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_alter_devicecategory_communication_waiting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(help_text='实例名称', max_length=20, verbose_name='实例名称')),
                ('parameters', models.JSONField(help_text='参数key和参数值组成的键值对', verbose_name='命令实例内容')),
                ('device_origin', models.CharField(choices=[('C', '设备类型'), ('D', '设备')], help_text='设备源类型', max_length=20, verbose_name='设备源类型')),
                ('category', models.ForeignKey(blank=True, help_text='设备类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_instance', to='equipments.devicecategory', verbose_name='设备类型')),
                ('category_command', models.ForeignKey(help_text='设备类型命令', on_delete=django.db.models.deletion.CASCADE, related_name='command_instance', to='equipments.devicecategorycommands', verbose_name='设备类型命令')),
                ('device', models.ForeignKey(blank=True, help_text='设备', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_instance', to='equipments.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '命令实例',
                'verbose_name_plural': '命令实例',
                'ordering': ('-id',),
            },
        ),
    ]
