# Generated by Django 4.2.10 on 2024-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='device_origin',
            field=models.CharField(choices=[('C', '设备类型'), ('D', '设备')], help_text='设备源类型', max_length=5, verbose_name='设备源类型'),
        ),
    ]
