# Generated by Django 4.2.10 on 2024-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_command_device_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='logo',
            field=models.ImageField(blank=True, help_text='设备类型logo', null=True, upload_to='', verbose_name='设备类型logo'),
        ),
    ]
