# Generated by Django 4.2.10 on 2024-02-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_devicecategory_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='logo',
            field=models.ImageField(blank=True, help_text='设备logo', null=True, upload_to='', verbose_name='设备logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, help_text='产品logo', null=True, upload_to='', verbose_name='产品logo'),
        ),
    ]
