# Generated by Django 4.2.10 on 2024-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_alter_device_logo_alter_product_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategoryAttrTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='属性名称', max_length=100, null=True, verbose_name='属性名称')),
                ('desc', models.TextField(blank=True, help_text='属性描述', null=True, verbose_name='属性描述')),
                ('key', models.CharField(help_text='属性标识符', max_length=100, verbose_name='属性标识符')),
                ('attr_type', models.CharField(blank=True, choices=[('U', '设备上报'), ('D', '云端下发'), ('CS', '双向传输'), ('CP', '云端私有')], help_text='属性类型', max_length=50, null=True, verbose_name='属性类型')),
                ('data_type', models.CharField(choices=[('N', '数值(Number)'), ('B', '开关量(Boolean)'), ('T', '文本(String)'), ('E', '枚举(Enum)'), ('O', '键值对(Object)'), ('L', '列表(List)')], help_text='属性数据类型', max_length=20, verbose_name='属性数据类型')),
                ('data_specs', models.JSONField(blank=True, help_text='属性约束', null=True, verbose_name='属性约束')),
            ],
            options={
                'verbose_name': '设备类型-属性模板',
                'verbose_name_plural': '设备类型-属性模板',
            },
        ),
    ]
