# Generated by Django 4.2.10 on 2024-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_devicecategoryattrtemplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategoryattrtemplates',
            name='name',
            field=models.CharField(blank=True, help_text='属性名称', max_length=100, null=True, unique=True, verbose_name='属性名称'),
        ),
    ]
