# Generated by Django 4.2.10 on 2024-03-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_alter_devicecategoryattrtemplates_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategorycommands',
            name='device_category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devicecategoryevents',
            name='device_category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
    ]
