# Generated by Django 4.2.10 on 2024-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_alter_devicecategorycommands_device_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategoryattrs',
            name='is_scene',
        ),
        migrations.AddField(
            model_name='devicecategoryattrs',
            name='attr_scene_action',
            field=models.BooleanField(default=True, help_text='是否参与场景动作', verbose_name='是否参与场景动作'),
        ),
        migrations.AddField(
            model_name='devicecategoryattrs',
            name='attr_scene_condition',
            field=models.BooleanField(default=True, help_text='是否参与场景条件', verbose_name='是否参与场景条件'),
        ),
    ]
