# Generated by Django 4.2.10 on 2024-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_remove_devicecategoryattrs_is_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_id',
            field=models.CharField(blank=True, help_text='在同一个设备类型下唯一', max_length=64, null=True, verbose_name='设备序列号'),
        ),
    ]
