# Generated by Django 4.2.10 on 2024-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_device_serial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategoryattrtemplates',
            name='attr_scene_action',
            field=models.BooleanField(default=True, help_text='是否参与场景动作，上报属性必须设置为False', verbose_name='是否参与场景动作'),
        ),
        migrations.AddField(
            model_name='devicecategoryattrtemplates',
            name='attr_scene_condition',
            field=models.BooleanField(default=True, help_text='是否参与场景条件，下发属性必须设置为False', verbose_name='是否参与场景条件'),
        ),
    ]
