# Generated by Django 4.2.10 on 2024-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_devicecategoryattrtemplates_attr_scene_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='ui_key',
            field=models.CharField(blank=True, help_text='个性化UI标识，形如：“UK_xxxxxxxxxx”', max_length=30, null=True, verbose_name='个性化UI'),
        ),
    ]
