# Generated by Django 4.2.10 on 2024-06-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_devicecategory_ui_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcpRegistFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='注册帧标识符', max_length=20, verbose_name='注册帧标识符')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, to='equipments.devicecategory', unique=True, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': 'TCP注册帧',
                'verbose_name_plural': 'TCP注册帧',
            },
        ),
    ]
