# Generated by Django 4.2.10 on 2024-06-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0015_tcpregistframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='ui_key',
            field=models.JSONField(blank=True, help_text='json字符串。包含个性化UI标识（如“UK_xxxxxxxxxx”）及相关配置信息', null=True, verbose_name='个性化UI'),
        ),
        migrations.AlterField(
            model_name='tcpregistframe',
            name='device_category',
            field=models.OneToOneField(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, to='equipments.devicecategory', verbose_name='设备类型'),
        ),
    ]
