# Generated by Django 4.2.10 on 2024-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_alter_devicecategory_ui_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='ui_params',
            field=models.JSONField(blank=True, help_text='json字符串。包含个性化UI标识（如“UK_xxxxxxxxxx”）及相关配置信息', null=True, verbose_name='个性化UI'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='ui_key',
            field=models.JSONField(blank=True, help_text='待废弃', null=True, verbose_name='个性化UI'),
        ),
    ]
