# Generated by Django 4.2.10 on 2024-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_devicecategory_ui_params_alter_devicecategory_ui_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategory',
            name='ui_key',
        ),
    ]
