# Generated by Django 4.2.13 on 2024-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0018_remove_devicecategory_ui_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='ignore_disconnection',
            field=models.BooleanField(default=False, help_text='是否忽略设备链路断开', verbose_name='是否忽略设备链路断开'),
        ),
    ]
