# Generated by Django 4.2.16 on 2024-10-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0019_devicecategory_ignore_disconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTransferCfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_flow', models.CharField(choices=[('up', '上行'), ('down', '下行')], help_text='数据流向', max_length=10, verbose_name='数据流向')),
                ('topic', models.CharField(db_index=True, help_text='映射topic', max_length=200, verbose_name='映射topic')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('data_stream', models.ForeignKey(blank=True, help_text='自定义数据流', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.devicecategorydatastream', verbose_name='自定义数据流')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='topic_cfgs', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': 'topic映射表',
                'verbose_name_plural': 'topic映射表',
            },
        ),
    ]
