# Generated by Django 4.2.16 on 2024-10-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_topictransfercfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategorymodbus',
            name='data_stream',
            field=models.ForeignKey(blank=True, help_text='自定义数据流', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.devicecategorydatastream', verbose_name='自定义数据流'),
        ),
    ]
