# Generated by Django 4.2.16 on 2024-10-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0021_alter_devicecategorymodbus_data_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcpregistframe',
            name='device_category',
            field=models.OneToOneField(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='tcp_register_frame', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
    ]
