# Generated by Django 4.2.17 on 2025-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0022_alter_tcpregistframe_device_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategoryattrs',
            name='is_manual_updated',
            field=models.BooleanField(default=False, help_text='是否可手动更新', verbose_name='是否可手动更新'),
        ),
    ]
