# Generated by Django 4.2.17 on 2025-01-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0023_devicecategoryattrs_is_manual_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("port", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "设备-TCP连接信息",
                "verbose_name_plural": "设备-TCP连接信息",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="conn_tcp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipments.tcpserver",
                verbose_name="tcp连接地址-端口",
            ),
        ),
    ]
