# Generated by Django 4.2.17 on 2025-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0024_tcpserver_device_conn_tcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='communication_waiting_time',
            field=models.IntegerField(blank=True, default=60000, help_text='通讯等待时间', null=True, verbose_name='通讯等待时间'),
        ),
    ]
