# Generated by Django 4.2.17 on 2025-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0026_alter_devicecategory_communication_waiting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr',
            field=models.CharField(blank=True, help_text='二维码标识：通常以"QR_"开头，如"QR_A250300001"', max_length=16, null=True, unique=True, verbose_name='二维码标识'),
        ),
    ]
