# Generated by Django 4.2.20 on 2025-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0027_device_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedproduct',
            name='product_key',
            field=models.CharField(default=None, help_text='形如: company.product.version', max_length=200, null=True, unique=True, verbose_name='产品识别码'),
        ),
        migrations.AlterField(
            model_name='fixedproduct',
            name='fix_string',
            field=models.CharField(default=None, help_text='与“产品识别码”功能相同，由系统自动生成，不可修改，形如: PK_Ab123', max_length=20, unique=True, verbose_name='产品识别标识'),
        ),
    ]
