# Generated by Django 4.2.20 on 2025-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0028_fixedproduct_product_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedproduct',
            options={'verbose_name': '公共产品库', 'verbose_name_plural': '公共产品库'},
        ),
        migrations.AlterModelOptions(
            name='manufacturerinfo',
            options={'verbose_name': '厂商', 'verbose_name_plural': '厂商'},
        ),
        migrations.RemoveField(
            model_name='fixedproduct',
            name='product_key',
        ),
        migrations.AddField(
            model_name='fixedproduct',
            name='product_code',
            field=models.CharField(default=None, help_text='形如: company.product.specification.version', max_length=200, null=True, unique=True, verbose_name='产品识别码'),
        ),
        migrations.AddField(
            model_name='manufacturerinfo',
            name='key',
            field=models.CharField(default=None, help_text='厂商Key，如："ibm", "apple"', max_length=30, null=True, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='fixedproduct',
            name='fix_string',
            field=models.CharField(default=None, help_text='与“产品识别码”功能相同，由系统自动生成，不可修改，形如: PK_Ab123', max_length=20, unique=True, verbose_name='产品Key'),
        ),
        migrations.AlterField(
            model_name='manufacturerinfo',
            name='name',
            field=models.CharField(help_text='厂商名称', max_length=60, unique=True, verbose_name='名称'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
