# Generated by Django 4.2.20 on 2025-04-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0029_alter_fixedproduct_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedproduct',
            old_name='product_code',
            new_name='code',
        ),
    ]
