# Generated by Django 4.2.20 on 2025-04-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0030_rename_product_code_fixedproduct_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedproduct',
            old_name='fix_string',
            new_name='key',
        ),
    ]
