# Generated by Django 4.2.20 on 2025-04-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0031_rename_fix_string_fixedproduct_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='f_product',
            field=models.ForeignKey(blank=True, help_text='当产品类型quote_product为产品类型（P）时，必传', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_product_categorise', to='equipments.fixedproduct', verbose_name='产品类型'),
        ),
    ]
