# Generated by Django 4.2.20 on 2025-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0032_devicecategory_f_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategory',
            name='fixed_product',
        ),
    ]
