# Generated by Django 4.2.20 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0033_remove_devicecategory_fixed_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerinfo',
            name='key',
        ),
        migrations.AddField(
            model_name='manufacturerinfo',
            name='code',
            field=models.CharField(default=None, help_text='如："ibm", "apple"', max_length=30, null=True, unique=True, verbose_name='厂商识别码'),
        ),
    ]
