# Generated by Django 4.2.20 on 2025-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0034_remove_manufacturerinfo_key_manufacturerinfo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='online_cfg',
            field=models.JSONField(blank=True, help_text='设备在线状态基于属性配置{"attr_key": "state", "on_value": 1, "attr_type": "N"}', null=True, verbose_name='设备在线状态基于属性配置'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='online_delay_time',
            field=models.IntegerField(blank=True, default=300, help_text='设备在线延迟时间', null=True, verbose_name='设备在线延迟时间'),
        ),
    ]
