# Generated by Django 4.2.20 on 2025-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0035_devicecategory_online_cfg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictransfercfg',
            name='subscribe_topic',
            field=models.CharField(blank=True, help_text='订阅topic', max_length=200, null=True, verbose_name='订阅topic'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='online_cfg',
            field=models.JSONField(blank=True, help_text='设备在线状态基于属性配置{"attr_key": "state", "attr_value": 1, "attr_type": "N"}', null=True, verbose_name='设备在线状态基于属性配置'),
        ),
    ]
