# Generated by Django 4.2.20 on 2025-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0036_topictransfercfg_subscribe_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='conn_cfg',
            field=models.TextField(blank=True, help_text='连接信息', null=True, verbose_name='连接信息'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='is_send_response',
            field=models.BooleanField(default=False, help_text='是否接收响应', verbose_name='是否接收响应'),
        ),
    ]
