# Generated by Django 4.2.20 on 2025-06-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0037_devicecategory_conn_cfg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='厂商', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mf_fixed_products', to='equipments.manufacturerinfo', verbose_name='厂商'),
        ),
        migrations.CreateModel(
            name='ManufacturerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('level', models.IntegerField(choices=[(10, '拥有者'), (20, '管理员'), (30, '应用用户')], default=10, help_text='权限级别', verbose_name='权限级别')),
                ('desc', models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(blank=True, help_text='项目成员邀请人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_mf_users', to=settings.AUTH_USER_MODEL, verbose_name='项目成员邀请人')),
                ('manufacturer', models.ForeignKey(help_text='厂商', on_delete=django.db.models.deletion.CASCADE, related_name='mf_users', to='equipments.manufacturerinfo', verbose_name='厂商')),
                ('user', models.ForeignKey(help_text='厂商人员', on_delete=django.db.models.deletion.CASCADE, related_name='user_manufacturers', to=settings.AUTH_USER_MODEL, verbose_name='厂商人员')),
            ],
            options={
                'verbose_name': '厂商人员表',
                'verbose_name_plural': '厂商人员表',
            },
        ),
    ]
