# Generated by Django 4.2.20 on 2025-06-23 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0038_fixedproduct_manufacturer_manufactureruser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manufactureruser',
            unique_together={('manufacturer', 'user')},
        ),
    ]
