# Generated by Django 4.2.20 on 2025-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0039_alter_manufactureruser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedproduct',
            name='is_published',
            field=models.BooleanField(default=True, help_text='是否已发布', verbose_name='是否已发布'),
        ),
    ]
