# Generated by Django 4.2.20 on 2025-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0040_fixedproduct_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='key',
            field=models.CharField(blank=True, help_text='设备类型唯一标识：以"DC_XXX"开头，如"DC_NRXse678"', max_length=16, null=True, unique=True, verbose_name='设备类型唯一标识'),
        ),
    ]
