# Generated by Django 4.2.20 on 2025-07-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0041_devicecategory_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='version',
            field=models.CharField(default='v1', help_text='版本号', max_length=10, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='com_gateway',
            field=models.ForeignKey(blank=True, help_text='所属设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.device', verbose_name='所属设备'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='node_type',
            field=models.CharField(choices=[('CG', '直接上网设备'), ('SD', '间接上网设备')], help_text='设备接入类型', max_length=20, verbose_name='设备接入类型'),
        ),
    ]
