# Generated by Django 4.2.20 on 2025-07-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0042_devicecategory_version_alter_device_com_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='is_auto_create',
            field=models.BooleanField(default=True, help_text='是否允许自动创建设备', verbose_name='是否允许自动创建设备'),
        ),
        migrations.CreateModel(
            name='CloudGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='云网关名称', max_length=100, verbose_name='云网关名称')),
                ('key', models.CharField(help_text='云网关唯一标识：以"CG_"开头，如"CG_XXX"', max_length=68, unique=True, verbose_name='云网关唯一标识')),
                ('device_field', models.CharField(help_text='设备标识字段', max_length=100, verbose_name='设备标识字段')),
                ('receive_data', models.JSONField(blank=True, help_text='接收数据预览', null=True, verbose_name='接收数据预览')),
                ('client_ips', models.JSONField(blank=True, help_text='ip白名单', null=True, verbose_name='ip白名单')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('data_stream', models.ForeignKey(help_text='自定义数据流', on_delete=django.db.models.deletion.CASCADE, to='equipments.devicecategorydatastream', verbose_name='自定义数据流')),
                ('device_category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='cloud_gateways', to='equipments.devicecategory', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '云网关',
                'verbose_name_plural': '云网关',
            },
        ),
    ]
