# Generated by Django 4.2.20 on 2025-08-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0043_devicecategory_is_auto_create_cloudgateway'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureruser',
            options={'verbose_name': '厂商人员', 'verbose_name_plural': '厂商人员'},
        ),
    ]
