# Generated by Django 4.2.20 on 2025-08-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0043_devicecategory_is_auto_create_cloudgateway'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureruser',
            options={'verbose_name': '厂商人员', 'verbose_name_plural': '厂商人员'},
        ),
        migrations.RemoveField(
            model_name='cloudgateway',
            name='receive_data',
        ),
        migrations.AlterField(
            model_name='cloudgateway',
            name='data_stream',
            field=models.ForeignKey(blank=True, help_text='自定义数据流', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.devicecategorydatastream', verbose_name='自定义数据流'),
        ),
        migrations.AlterField(
            model_name='cloudgateway',
            name='device_category',
            field=models.ForeignKey(blank=True, help_text='设备类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_gateways', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='cloudgateway',
            name='device_field',
            field=models.CharField(blank=True, help_text='设备标识字段', max_length=100, null=True, verbose_name='设备标识字段'),
        ),
    ]
