# Generated by Django 4.2.20 on 2025-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0044_alter_manufactureruser_options'),
        ('equipments', '0044_alter_manufactureruser_options_and_more'),
    ]

    operations = [
    ]
