# Generated by Django 4.2.20 on 2025-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0045_merge_20250807_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudgateway',
            name='desc',
            field=models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述'),
        ),
    ]
