# Generated by Django 4.2.20 on 2025-08-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_uuid'),
        ('equipments', '0046_cloudgateway_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudgateway',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_cloud_gateways', to='users.projects', verbose_name='项目'),
        ),
    ]
