# Generated by Django 4.2.20 on 2025-08-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0047_cloudgateway_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureruser',
            options={'verbose_name': '厂商成员', 'verbose_name_plural': '厂商成员'},
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_manufacturers', to=settings.AUTH_USER_MODEL, verbose_name='厂商成员'),
        ),
    ]
