# Generated by Django 4.2.20 on 2025-08-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0048_alter_manufactureruser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topictransfercfg',
            options={'verbose_name': 'topic映射', 'verbose_name_plural': 'topic映射'},
        ),
    ]
