# Generated by Django 4.2.20 on 2025-08-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0049_alter_topictransfercfg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedproduct',
            options={'verbose_name': '公共产品', 'verbose_name_plural': '公共产品'},
        ),
    ]
