# Generated by Django 4.2.20 on 2025-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0050_alter_fixedproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategoryattrs',
            name='is_show_app',
            field=models.BooleanField(default=True, help_text='是否在移动端展示', verbose_name='是否在移动端展示'),
        ),
    ]
