# Generated by Django 4.2.20 on 2025-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0051_devicecategoryattrs_is_show_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerinfo',
            name='logo',
            field=models.TextField(blank=True, help_text='厂商logo', null=True, verbose_name='厂商logo'),
        ),
    ]
