# Generated by Django 4.2.20 on 2025-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0052_manufacturerinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudgateway',
            name='action_conf',
            field=models.JSONField(blank=True, help_text='自定义响应云函数配置', null=True, verbose_name='自定义响应云函数配置'),
        ),
        migrations.AddField(
            model_name='cloudgateway',
            name='is_custom_resp',
            field=models.BooleanField(default=False, help_text='是否自定义响应', verbose_name='是否自定义响应'),
        ),
    ]
