# Generated by Django 4.2.20 on 2025-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0053_cloudgateway_action_conf_cloudgateway_is_custom_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='access_protocol',
            field=models.CharField(blank=True, choices=[('SP', 'EZtCloud标准协议'), ('SGP', 'EZtCloud标准网关协议'), ('MRP', 'ModBus RTU透传协议'), ('MGRP', 'ModBus RTU云网关协议'), ('OTHER', '其它')], help_text='设备接入协议', max_length=30, null=True, verbose_name='设备接入协议'),
        ),
    ]
