# Generated by Django 4.2.20 on 2025-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0054_alter_devicecategory_access_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategorydatastream',
            name='device_subscribe_topic',
            field=models.CharField(blank=True, help_text='设备订阅需开放权限', max_length=100, null=True, verbose_name='设备订阅Topic通配符'),
        ),
        migrations.AddField(
            model_name='devicecategorydatastream',
            name='topic_type',
            field=models.CharField(blank=True, choices=[('parameter', '自定义参数'), ('mapping', 'topic映射')], help_text='自定义Topic模式', max_length=100, null=True, verbose_name='自定义Topic模式'),
        ),
        migrations.AlterField(
            model_name='devicecategorydatastream',
            name='publish_topic_key',
            field=models.CharField(blank=True, help_text='高级模式发布Topic', max_length=100, null=True, verbose_name='高级模式发布Topic'),
        ),
        migrations.AlterField(
            model_name='devicecategorydatastream',
            name='subscribe_topic_key',
            field=models.CharField(blank=True, help_text='高级模式订阅Topic', max_length=100, null=True, verbose_name='高级模式订阅Topic'),
        ),
    ]
