# Generated by Django 4.2.20 on 2025-09-23 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0055_devicecategorydatastream_device_subscribe_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMappingCfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_flow', models.CharField(choices=[('up', '上行'), ('down', '下行')], help_text='数据流向', max_length=10, verbose_name='数据流向')),
                ('topic', models.CharField(db_index=True, help_text='映射topic', max_length=200, verbose_name='映射topic')),
                ('subscribe_topic', models.CharField(blank=True, help_text='订阅topic', max_length=200, null=True, verbose_name='订阅topic')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'topic映射配置',
                'verbose_name_plural': 'topic映射配置',
                'unique_together': {('data_flow', 'topic', 'subscribe_topic')},
            },
        ),
    ]
