# Generated by Django 4.2.20 on 2025-10-11 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0057_delete_topicmappingcfg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedproduct',
            name='publish_state',
            field=models.CharField(choices=[('unpublished', '未发布'), ('published', '已发布'), ('recalled', '已撤回')], default='published', help_text='发布状态', max_length=20, verbose_name='发布状态'),
        ),
        migrations.CreateModel(
            name='FixedProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(help_text='文件路径', verbose_name='文件路径')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('file_info', models.JSONField(blank=True, help_text='文件信息', null=True, verbose_name='文件信息')),
                ('f_product', models.ForeignKey(help_text='产品类型', on_delete=django.db.models.deletion.CASCADE, related_name='fixed_product_files', to='equipments.fixedproduct', verbose_name='产品类型')),
            ],
            options={
                'verbose_name': '公共产品文档',
                'verbose_name_plural': '公共产品文档',
            },
        ),
    ]
