# Generated by Django 4.2.20 on 2025-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0058_fixedproduct_publish_state_fixedproductfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='尚未命名', help_text='设备名称', max_length=100, verbose_name='设备名称'),
        ),
    ]
