# Generated by Django 4.2.20 on 2025-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0059_alter_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='tag_conf',
            field=models.JSONField(blank=True, help_text='标签', null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='devicecategorydatastream',
            name='is_auth',
            field=models.BooleanField(default=True, help_text='topic权限是否认证', verbose_name='topic权限是否认证'),
        ),
    ]
