# Generated by Django 4.2.20 on 2025-12-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0060_devicecategory_tag_conf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicTransferCfg',
        ),
    ]
