# Generated by Django 4.2.20 on 2026-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0061_delete_topictransfercfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='communication_waiting_time',
            field=models.IntegerField(blank=True, default=2000, help_text='通讯等待时间(500-5000)ms', null=True, verbose_name='通讯等待时间'),
        ),
    ]
