# Generated by Django 4.2.20 on 2026-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0062_alter_devicecategory_communication_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_id',
            field=models.CharField(blank=True, db_index=True, help_text='在同一个设备类型下唯一', max_length=64, null=True, verbose_name='设备序列号'),
        ),
    ]
