# Generated by Django 4.2.20 on 2026-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0063_alter_device_serial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='control_attr_conf',
            field=models.JSONField(blank=True, help_text='移动端属性控制配置', null=True, verbose_name='属性控制配置'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='show_attr_conf',
            field=models.JSONField(blank=True, help_text='移动端属性显示配置', null=True, verbose_name='属性显示配置'),
        ),
    ]
