# Generated by Django 4.2.20 on 2026-02-26 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0064_devicecategory_control_attr_conf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedproduct',
            name='documentation',
            field=models.JSONField(blank=True, help_text='包含设备文档路径、文档版本等信息', null=True, verbose_name='文档信息'),
        ),
        migrations.CreateModel(
            name='FixedProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='版本号，如 v1.0.0', max_length=20, verbose_name='版本号')),
                ('conf', models.JSONField(help_text='包含功能定义、自定义数据流、规则、告警、任务、topic映射等信息（不包含文档信息）', verbose_name='版本配置信息')),
                ('publish_state', models.CharField(choices=[('unpublished', '未发布'), ('published', '已发布'), ('recalled', '已撤回')], default='unpublished', help_text='发布状态', max_length=20, verbose_name='发布状态')),
                ('is_default', models.BooleanField(default=False, help_text='标记为默认版本的将被优先使用', verbose_name='是否默认版本')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('fixed_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='equipments.fixedproduct', verbose_name='公共产品')),
            ],
            options={
                'unique_together': {('fixed_product', 'version')},
            },
        ),
    ]
