# Generated by Django 4.2.20 on 2026-02-26 09:00

from django.db import migrations


def migrate_fixed_product_to_version(apps, schema_editor):
    """将现有的 FixedProduct 数据迁移到 FixedProductVersion"""
    FixedProduct = apps.get_model('equipments', 'FixedProduct')
    FixedProductVersion = apps.get_model('equipments', 'FixedProductVersion')
    
    # 遍历所有现有的 FixedProduct 实例
    for fixed_product in FixedProduct.objects.all():
        # 创建对应的 FixedProductVersion 实例
        version = FixedProductVersion(
            fixed_product=fixed_product,
            version=fixed_product.version or 'v1.0.0',
            conf=fixed_product.conf,
            publish_state=fixed_product.publish_state,
            is_default=True,  # 将第一个版本设置为默认版本
            created_time=fixed_product.created_time
        )
        version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0065_fixedproduct_documentation_fixedproductversion'),
    ]

    operations = [
        migrations.RunPython(migrate_fixed_product_to_version),
    ]
