# Generated by Django 4.2.20 on 2026-02-26 11:42

from django.db import migrations
from django.utils import timezone


def copy_conf_to_versions(apps, schema_editor):
    """将FixedProduct的conf字段（除文档外）复制到FixedProductVersion中"""
    FixedProduct = apps.get_model('equipments', 'FixedProduct')
    FixedProductVersion = apps.get_model('equipments', 'FixedProductVersion')
    
    # 遍历所有公共产品
    for fixed_product in FixedProduct.objects.all():
        # 检查是否已有版本
        if not fixed_product.versions.exists() and fixed_product.conf:
            # 创建版本实例
            version = FixedProductVersion(
                fixed_product=fixed_product,
                version=fixed_product.version or 'v1.0.0',
                conf=fixed_product.conf,  # 复制整个conf字段
                publish_state=fixed_product.publish_state,
                is_default=True,  # 设为默认版本
                created_time=timezone.now()
            )
            version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0066_fixedproduct_to_version'),
    ]

    operations = [
        migrations.RunPython(copy_conf_to_versions),
    ]
