# Generated by Django 4.2.20 on 2026-02-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0069_auto_20260226_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='source_fixed_product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source_device_categories',
                to='equipments.fixedproduct',
                verbose_name='来源公共产品',
            ),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='source_fixed_product_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source_device_categories',
                to='equipments.fixedproductversion',
                verbose_name='来源公共产品版本',
            ),
        ),
    ]

