# Generated by Django 4.2.20 on 2026-02-27 00:10

import re
from django.db import migrations


def normalize_product_code(code):
    if not code:
        return code
    code = str(code).strip()
    code = re.sub(r'(?:\.)?(?:v)?\d+(?:\.\d+){0,3}$', '', code, flags=re.IGNORECASE)
    return code.rstrip('.') or code


def migrate_fixed_product_code(apps, schema_editor):
    FixedProduct = apps.get_model('equipments', 'FixedProduct')

    seen = set(FixedProduct.objects.exclude(code__isnull=True).values_list('code', flat=True))

    for product in FixedProduct.objects.all():
        old_code = product.code
        new_code = normalize_product_code(old_code)
        if not new_code or new_code == old_code:
            continue

        final_code = new_code
        idx = 1
        while final_code in seen:
            final_code = f"{new_code}.{idx}"
            idx += 1

        seen.add(final_code)
        product.code = final_code
        product.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0070_devicecategory_source_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_fixed_product_code, migrations.RunPython.noop),
    ]

