# Generated by Django 4.2.20 on 2026-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0072_fixedproductversion_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedproduct',
            name='code',
            field=models.CharField(default=None, help_text='形如: company.product.specification（不含版本信息）', max_length=200, null=True, unique=True, verbose_name='产品识别码'),
        ),
    ]
