# Generated by Django 4.2.20 on 2026-03-18 00:00

from django.db import migrations


def forwards(apps, schema_editor):
    DeviceCategory = apps.get_model('equipments', 'DeviceCategory')
    FixedProductVersion = apps.get_model('equipments', 'FixedProductVersion')

    default_versions = FixedProductVersion.objects.filter(
        is_default=True
    ).values_list('fixed_product_id', 'id')
    default_version_map = {fixed_product_id: version_id for fixed_product_id, version_id in default_versions}

    qs = DeviceCategory.objects.filter(
        source_fixed_product_version__isnull=True,
        f_product__isnull=False
    )

    for device_category in qs.iterator():
        version_id = default_version_map.get(device_category.f_product_id)
        if not version_id:
            continue
        update_fields = []
        if not device_category.source_fixed_product_id:
            device_category.source_fixed_product_id = device_category.f_product_id
            update_fields.append('source_fixed_product')
        device_category.source_fixed_product_version_id = version_id
        update_fields.append('source_fixed_product_version')
        device_category.f_product_id = None
        update_fields.append('f_product')
        device_category.save(update_fields=update_fields)


def backwards(apps, schema_editor):
    # 不回滚数据，避免误清理已补齐的来源版本信息
    return


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0073_alter_fixedproduct_code'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
