# Generated by Django 4.2.20 on 2026-03-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0074_backfill_devicecategory_source_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategory',
            name='f_product',
        ),
    ]
