# Generated by Django 4.2.20 on 2026-03-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0075_remove_devicecategory_f_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedproduct',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='fixedproduct',
            name='publish_state',
        ),
    ]
