# Generated by Django 4.2.20 on 2026-03-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0076_remove_fixedproduct_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategory',
            name='version',
        ),
    ]
