# Generated by Django 4.2.20 on 2026-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0077_remove_devicecategory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='scene_action',
            field=models.BooleanField(default=True, help_text='开启后，该设备类型的属性可作为智能场景的执行动作。', verbose_name='属性可作为智能场景执行动作'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='scene_condition',
            field=models.BooleanField(default=True, help_text='开启后，该设备类型的属性可作为智能场景的触发器。', verbose_name='属性可作为智能场景触发器'),
        ),
    ]
