# Generated by Django 4.2.20 on 2026-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0078_alter_devicecategory_scene_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='record_auto_close_time',
            field=models.DateTimeField(blank=True, help_text='开启消息日志后自动关闭时间', null=True, verbose_name='消息日志自动关闭时间'),
        ),
    ]

