# 请保留这一行注释，以避免utf-8 BOM问题
server {
    listen 8084 default_server;

    root /workspace/isw_v2/frontend_mobile_dist_local;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
