# Generated by Django 4.2.10 on 2024-02-07 11:33

from backend.apps.common.fields import CharNullField
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(default='匿名', help_text='中文名', max_length=50, verbose_name='中文名')),
                ('mobile', CharNullField(blank=True, help_text='手机号', max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('email', CharNullField(blank=True, help_text='邮箱', max_length=50, null=True, unique=True, verbose_name='邮箱')),
                ('avatar', models.TextField(blank=True, help_text='用户头像', null=True, verbose_name='用户头像')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=150, null=True, verbose_name='地址')),
                ('is_sys', models.BooleanField(default=True, help_text='是否系统内用户', verbose_name='是否系统内用户')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('token', models.CharField(blank=True, help_text='机器用户可基于token访问API', max_length=20, null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='创建者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('default_city', models.ForeignKey(blank=True, help_text='默认城市', null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.area')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='项目名称', max_length=100, null=True, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, help_text='项目描述', null=True, verbose_name='项目描述')),
                ('project_key', models.CharField(blank=True, help_text='项目连接标识', max_length=100, null=True, unique=True, verbose_name='ProjectKey')),
                ('project_password', models.CharField(blank=True, help_text='项目连接秘钥', max_length=100, null=True, verbose_name='ProjectSecret')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('creator', models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='设备组名称', max_length=100, verbose_name='设备组名称')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('desc', models.TextField(blank=True, help_text='设备分组描述信息', null=True, verbose_name='设备分组描述信息')),
                ('project', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_units', to='users.projects', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '设备组',
                'verbose_name_plural': '设备组',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_project',
            field=models.ForeignKey(blank=True, help_text='移动端用户默认项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.projects', verbose_name='默认项目'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, '拥有者'), (20, '管理员'), (30, '应用用户')], default=10, help_text='权限级别', verbose_name='权限级别')),
                ('desc', models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述')),
                ('is_join_project', models.BooleanField(default=False, verbose_name='是否加入项目')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否从项目中移除', verbose_name='是否从项目中移除')),
                ('creator', models.ForeignKey(blank=True, help_text='项目成员记录创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_users', to=settings.AUTH_USER_MODEL, verbose_name='项目成员记录创建人')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='users.projects', verbose_name='项目')),
                ('user', models.ForeignKey(blank=True, help_text='项目成员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_members', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
            ],
            options={
                'verbose_name': '项目成员明细',
                'verbose_name_plural': '项目成员明细',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
