# Generated by Django 4.2.10 on 2024-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.CharField(help_text='通常以"PR_"开头，如"PR_xxxxxxxxxx', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_key',
            field=models.CharField(blank=True, help_text='仅为兼容暂时保留，即将被id代替', max_length=30, null=True, unique=True, verbose_name='ProjectKey'),
        ),
    ]
