# Generated by Django 4.2.10 on 2024-02-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_projects_id_alter_projects_project_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_key',
        ),
    ]
