# Generated by Django 4.2.10 on 2024-02-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_projects_project_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(default='尚未命名', help_text='项目名称', max_length=100, verbose_name='项目名称'),
        ),
    ]
