# Generated by Django 4.2.10 on 2024-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_projects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='monitor_screen',
            field=models.CharField(blank=True, help_text='形如："MS_xxxxxxxxxx"', max_length=30, null=True, verbose_name='监控大屏模板key'),
        ),
        migrations.AddField(
            model_name='projects',
            name='monitor_screen_params',
            field=models.JSONField(blank=True, help_text='不同的监控大屏模板，参数结构不同', null=True, verbose_name='监控大屏模板参数'),
        ),
    ]
