# Generated by Django 4.2.10 on 2024-05-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_projects_monitor_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_open_mqtt',
            field=models.BooleanField(default=False, help_text='是否开启open mqtt 推送', verbose_name='是否开启open mqtt 推送'),
        ),
    ]
