# Generated by Django 4.2.10 on 2024-05-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_projects_is_open_mqtt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='monitor_screen',
        ),
        migrations.AlterField(
            model_name='projects',
            name='monitor_screen_params',
            field=models.JSONField(blank=True, help_text='不同的看板模板，其参数结构不同，前端自存自取', null=True, verbose_name='看板参数'),
        ),
    ]
