# Generated by Django 4.2.16 on 2024-10-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_projects_monitor_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroups',
            name='order',
            field=models.IntegerField(default=0, help_text='序号', verbose_name='序号'),
        ),
    ]
