# Generated by Django 4.2.16 on 2024-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_devicegroups_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="bucket_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="时序数据库中的bucket的id",
                max_length=32,
                null=True,
                verbose_name="bucket_id",
            ),
        ),
    ]
