# Generated by Django 4.2.16 on 2024-11-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_projects_bucket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="bucket_disk_usage",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="硬盘使用量（MB）",
                null=True,
                verbose_name="硬盘使用量（MB）",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="bucket_disk_usage_time",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="硬盘使用量更新时间",
                null=True,
                verbose_name="硬盘使用量更新时间",
            ),
        ),
    ]
