# Generated by Django 4.2.20 on 2025-05-29 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_populate_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='跨系统用户关联的唯一标识', unique=True, verbose_name='UUID'),
        ),
    ]
