# Generated by Django 4.2.20 on 2025-08-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmembers',
            options={'verbose_name': '项目成员', 'verbose_name_plural': '项目成员'},
        ),
    ]
