# Generated by Django 4.2.20 on 2025-11-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_projectmembers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembers',
            name='project_ordering',
            field=models.IntegerField(default=0, help_text='用户项目排序', verbose_name='用户项目排序'),
        ),
        migrations.AddField(
            model_name='projects',
            name='ordering',
            field=models.IntegerField(default=0, help_text='对自己创建的项目排序', verbose_name='项目排序'),
        ),
    ]
