# Generated by Django 4.2.20 on 2025-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_projectmembers_project_ordering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='机器用户可基于token访问API', max_length=64, null=True),
        ),
    ]
