# Generated by Django 4.2.20 on 2025-12-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='auth_code',
            field=models.TextField(blank=True, default=None, help_text='项目授权码（明文+签名的JSON字符串）', null=True, verbose_name='项目授权码'),
        ),
    ]
