# Generated by Django 4.2.20 on 2026-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_projects_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_project_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='允许该用户拥有的项目数量，为 null 表示无限制', null=True, verbose_name='允许拥有的项目数'),
        ),
    ]
