# Generated by Django 4.2.20 on 2025-08-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'AI聊天-消息', 'verbose_name_plural': 'AI聊天-消息'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': 'AI聊天-会话', 'verbose_name_plural': 'AI聊天-会话'},
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table=None,
        ),
    ]
