# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('city_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='用于请求天气的id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subs', to='areas.area', verbose_name='上级行政区划')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'tb_areas',
            },
        ),
        migrations.CreateModel(
            name='CityMeteorological',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='时间', verbose_name='时间戳')),
                ('data', models.JSONField(blank=True, help_text='气象信息', null=True, verbose_name='气象信息')),
                ('city', models.ForeignKey(help_text='城市', on_delete=django.db.models.deletion.PROTECT, related_name='city_temps', to='areas.area', verbose_name='城市')),
            ],
            options={
                'verbose_name': '城市气象信息表',
                'verbose_name_plural': '城市气象信息表',
            },
        ),
    ]
