# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='场景名称', max_length=100, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, help_text='场景描述', null=True, verbose_name='场景描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('cfg_info', models.JSONField(blank=True, help_text='场景配置详情', null=True, verbose_name='场景配置详情')),
                ('trigger_type', models.CharField(blank=True, choices=[('timing', '定时'), ('attr_up', '属性上报')], help_text='触发类型', max_length=20, null=True, verbose_name='触发类型')),
                ('order', models.IntegerField(default=0, help_text='场景序号', verbose_name='场景序号')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_scenes', to='users.projects', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '场景设置',
                'verbose_name_plural': '场景设置',
            },
        ),
        migrations.CreateModel(
            name='SceneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_msg', models.JSONField(blank=True, help_text='设备执行动作', null=True, verbose_name='设备执行动作')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_scenes', to='equipments.device', verbose_name='设备')),
                ('scene', models.ForeignKey(blank=True, help_text='场景', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scene_devices', to='scenes.sceneconfig', verbose_name='场景')),
            ],
            options={
                'verbose_name': '场景设备',
                'verbose_name_plural': '场景设备',
            },
        ),
    ]
