# Generated by Django 4.2.10 on 2024-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneconfig',
            name='trigger_type',
            field=models.CharField(blank=True, help_text='触发类型', max_length=100, null=True, verbose_name='触发类型'),
        ),
    ]
