# Generated by Django 4.2.13 on 2024-08-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0019_devicecategory_ignore_disconnection'),
        ('scenes', '0002_alter_sceneconfig_trigger_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenedevice',
            options={'verbose_name': '场景动作', 'verbose_name_plural': '场景动作'},
        ),
        migrations.AlterField(
            model_name='scenedevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_scenes', to='equipments.device', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='scenedevice',
            name='scene',
            field=models.ForeignKey(blank=True, help_text='场景', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_devices', to='scenes.sceneconfig', verbose_name='场景'),
        ),
    ]
