# Generated by Django 4.2.16 on 2024-12-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_projects_bucket_disk_usage_and_more'),
        ('scenes', '0003_alter_scenedevice_options_alter_scenedevice_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneconfig',
            name='project',
            field=models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scenes', to='users.projects', verbose_name='所属组织'),
        ),
    ]
