# Generated by Django 4.2.20 on 2025-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0004_alter_sceneconfig_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneconfig',
            name='is_external_sys',
            field=models.BooleanField(default=False, help_text='是否外部系统', verbose_name='是否外部系统'),
        ),
    ]
