# Generated by Django 4.2.20 on 2025-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0005_sceneconfig_is_external_sys'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneconfig',
            name='tag_conf',
            field=models.JSONField(blank=True, help_text='标签', null=True, verbose_name='标签'),
        ),
    ]
