# Generated by Django 4.2.20 on 2025-12-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0006_sceneconfig_tag_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneconfig',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='场景序号', verbose_name='场景序号'),
        ),
    ]
