# Generated by Django 4.2.20 on 2026-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0008_sceneconfig_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneconfig',
            name='enabled',
            field=models.BooleanField(default=True, help_text='是否因授权过期而被关停。True=正常，False=因授权过期被关停。实际执行状态 = is_active AND enabled', verbose_name='是否因授权过期被关停'),
        ),
        migrations.AlterField(
            model_name='sceneconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='用户配置的启用/停用状态', verbose_name='是否启用'),
        ),
    ]
