# Generated by Django 4.2.20 on 2026-03-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0009_sceneconfig_enabled_alter_sceneconfig_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneconfig',
            name='interval_seconds',
            field=models.PositiveIntegerField(default=60, help_text='重发间隔(1-300秒)', verbose_name='重发间隔(1-300秒)'),
        ),
    ]
