# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import backend.apps.url_shortener.validators as url_shortener_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, validators=[url_shortener_validators.validate_url])),
                ('shortcode', models.CharField(blank=True, max_length=20, unique=True)),
                ('expiry_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sh_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='url_shortener.shorturl')),
            ],
        ),
    ]
