# Generated by Django 4.2.20 on 2025-12-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置键，例如 auth_code', max_length=255, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, help_text='配置值内容，auth_code 等', null=True, verbose_name='配置值')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
