# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_origin', models.CharField(choices=[('C', '设备类型'), ('D', '设备')], help_text='设备源类型', max_length=20, verbose_name='设备源类型')),
                ('name', models.CharField(blank=True, help_text='任务名称', max_length=50, null=True, verbose_name='任务名称')),
                ('desc', models.TextField(blank=True, help_text='任务描述', null=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('AD', '属性下发'), ('CD', '命令下发'), ('DDD', '自定义数据下发'), ('EM', '边缘任务')], help_text='任务类型', max_length=50, verbose_name='任务类型')),
                ('timing_type', models.CharField(blank=True, choices=[('once', '单次'), ('repeat', '重复'), ('interval', '间隔')], help_text='定时类型', max_length=50, null=True, verbose_name='定时类型')),
                ('handel', models.CharField(blank=True, help_text='操作内容', max_length=100, null=True, verbose_name='操作内容')),
                ('timing_conf', models.JSONField(blank=True, help_text='定时配置', null=True, verbose_name='定时配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('conf_for_type', models.JSONField(blank=True, help_text='类型为自定义数据下发需要pubish_type推送方式和data_stream自定义数据流', null=True, verbose_name='基于任务类型的相关配置')),
                ('is_record', models.BooleanField(default=False, help_text='任务 调试状态', verbose_name='任务 调试状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_tasks', to='equipments.devicecategory', verbose_name='设备类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tasks', to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TaskActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('AD_AD', '属性下发'), ('AD_CF', '云函数属性下发'), ('CD_CD', '命令下发'), ('CD_CF', '云函数命令下发'), ('CD_OG', 'OTA升级推送'), ('DDD_DD', '自定义下发'), ('DDD_CF', '云函数自定义下发'), ('DDD_MBRD', 'ModBus RTU 下发'), ('EM_MBRL', 'ModBus RTU 读取轮询')], help_text='操作类型', max_length=100, null=True, verbose_name='操作类型')),
                ('exec_conf', models.JSONField(blank=True, help_text='操作配置', null=True, verbose_name='操作配置')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_actions', to='tasks.tasks', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务操作',
                'verbose_name_plural': '任务操作',
            },
        ),
        migrations.CreateModel(
            name='DeviceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_time', models.DateTimeField(blank=True, help_text='执行时间', null=True, verbose_name='执行时间')),
                ('is_allow', models.BooleanField(default=True, verbose_name='是否允许设备使用')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tasks', to='equipments.device', verbose_name='设备')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_devices', to='tasks.tasks', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务设备',
                'verbose_name_plural': '任务设备',
            },
        ),
    ]
