# Generated by Django 4.2.10 on 2024-02-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_device_category_alter_device_com_gateway_and_more'),
        ('users', '0004_alter_projects_name'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='device_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_tasks', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='users.projects', verbose_name='项目'),
        ),
    ]
