# Generated by Django 4.2.17 on 2024-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_device_category_alter_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='timing_type',
            field=models.CharField(blank=True, choices=[('once', '单次'), ('repeat', '重复'), ('interval', '周期'), ('timing', '定时')], help_text='定时类型', max_length=50, null=True, verbose_name='定时类型'),
        ),
    ]
