# Generated by Django 4.2.20 on 2025-08-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_timing_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetasks',
            options={'verbose_name': '任务-设备级', 'verbose_name_plural': '任务-设备级'},
        ),
    ]
