# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmNoticeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='告警通知组名称', max_length=50, null=True, verbose_name='告警通知组名称')),
                ('desc', models.TextField(blank=True, help_text='告警通知组描述', null=True, verbose_name='告警通知组描述')),
                ('notice_types', models.JSONField(help_text='告警通知方式', verbose_name='告警通知方式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notice_conf', models.JSONField(help_text='告警组配置', verbose_name='告警组配置')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '告警通知组',
                'verbose_name_plural': '告警通知组',
            },
        ),
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_origin', models.CharField(choices=[('C', '设备类型'), ('D', '设备')], help_text='设备源类型', max_length=20, verbose_name='设备源类型')),
                ('name', models.CharField(blank=True, help_text='告警配置名称', max_length=50, null=True, verbose_name='告警配置名称')),
                ('condition', models.JSONField(blank=True, help_text='告警触发条件', null=True, verbose_name='告警触发条件')),
                ('degree', models.CharField(choices=[('10', '紧急'), ('20', '重要'), ('30', '普通')], help_text='告警级别', max_length=20, verbose_name='告警级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, help_text='告警备注', null=True, verbose_name='告警备注')),
                ('daily_notice_times_max', models.IntegerField(blank=True, help_text='每日通知次数上限', null=True, verbose_name='每日通知次数上限')),
                ('daily_notice_times_max_device', models.IntegerField(blank=True, help_text='但设备每日通知次数上限', null=True, verbose_name='单设备每日通知次数上限')),
                ('repeat_times', models.IntegerField(default=0, help_text='重复次数', verbose_name='重复次数')),
                ('endure_seconds', models.IntegerField(default=0, help_text='持续时间 (秒)', verbose_name='持续时间')),
                ('extra_conf', models.JSONField(blank=True, help_text='告警额外配置', null=True, verbose_name='告警额外配置')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '告警配置',
                'verbose_name_plural': '告警配置',
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allow', models.BooleanField(default=True, verbose_name='是否允许设备使用')),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_devices', to='alarms.alarms', verbose_name='告警')),
            ],
            options={
                'verbose_name': '告警设备',
                'verbose_name_plural': '告警设备',
            },
        ),
    ]
