# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alarms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarms',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_alarms', to='equipments.device', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='device_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_alarms', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='notice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alarms.alarmnoticegroup', verbose_name='告警通知组'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_alarms', to='users.projects', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='alarmnoticegroup',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='alarmnoticegroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_notice_groups', to='users.projects', verbose_name='项目'),
        ),
    ]
