# Generated by Django 4.2.10 on 2024-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alter_alarms_device_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmnoticegroup',
            name='notice_types',
        ),
        migrations.AddField(
            model_name='alarmnoticegroup',
            name='use_ding_robot',
            field=models.BooleanField(default=False, help_text='是否启用钉钉机器人通知', verbose_name='是否启用钉钉机器人通知'),
        ),
        migrations.AddField(
            model_name='alarmnoticegroup',
            name='use_member',
            field=models.BooleanField(default=False, help_text='是否启用成员通知', verbose_name='是否启用成员通知'),
        ),
    ]
