# Generated by Django 4.2.10 on 2024-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_remove_alarmnoticegroup_notice_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='allow_manual_clear',
            field=models.BooleanField(default=False, help_text='是否允许手动解除告警', verbose_name='是否允许手动解除告警'),
        ),
    ]
