# Generated by Django 4.2.13 on 2024-07-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_projects_monitor_screen_and_more'),
        ('alarms', '0005_alarms_allow_manual_clear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnoticegroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_notice_groups', to='users.projects', verbose_name='项目'),
        ),
    ]
