# Generated by Django 4.2.17 on 2024-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0006_alter_alarmnoticegroup_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='tag_conf',
            field=models.JSONField(blank=True, help_text='告警标签', null=True, verbose_name='告警标签'),
        ),
    ]
