# Generated by Django 4.2.17 on 2025-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alarms_tag_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='action_cfg',
            field=models.JSONField(blank=True, help_text='告警联动配置', null=True, verbose_name='告警联动配置'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='is_set_action',
            field=models.BooleanField(default=False, verbose_name='是否告警联动'),
        ),
    ]
