# Generated by Django 4.2.17 on 2025-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0008_alarms_action_cfg_alarms_is_set_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='trigger_source',
            field=models.CharField(choices=[('device_offline', '设备下线'), ('device_attr', '设备属性')], default='device_attr', help_text='告警触发源', max_length=20, verbose_name='告警触发源'),
        ),
    ]
