# Generated by Django 4.2.20 on 2025-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0009_alarms_trigger_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='is_external_sys',
            field=models.BooleanField(default=False, help_text='是否外部系统', verbose_name='是否外部系统'),
        ),
    ]
