# Generated by Django 4.2.20 on 2025-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0010_alarms_is_external_sys'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmnoticegroup',
            name='use_webhook',
            field=models.BooleanField(default=False, help_text='是否推送到外部URL', verbose_name='是否推送到外部URL'),
        ),
    ]
