# Generated by Django 4.2.20 on 2025-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0011_alarmnoticegroup_use_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='again_notify_numb',
            field=models.SmallIntegerField(default=0, help_text='再次通知次数', verbose_name='再次通知次数'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='interval_hours',
            field=models.SmallIntegerField(default=1, help_text='通知间隔(小时)', verbose_name='通知间隔(小时)'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='is_again_notify',
            field=models.BooleanField(default=False, help_text='告警持续时是否再次通知', verbose_name='告警持续时是否再次通知'),
        ),
    ]
