# Generated by Django 4.2.20 on 2025-08-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0012_alarms_again_notify_numb_alarms_interval_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicealarms',
            options={'verbose_name': '告警配置-设备级', 'verbose_name_plural': '告警配置-设备级'},
        ),
    ]
