# Generated by Django 4.2.20 on 2025-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0015_alter_domain_logo_alter_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='we_svc_alarm_on_tpl_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='持续告警通知模板ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_svc_alarm_restored_tpl_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='告警恢复消息模板ID'),
        ),
    ]
