# Generated by Django 4.2.20 on 2025-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0016_domain_we_svc_alarm_on_tpl_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='we_svc_alarm_on_tpl_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='告警持续消息模板ID'),
        ),
    ]
