# Generated by Django 4.2.20 on 2025-10-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0017_alter_domain_we_svc_alarm_on_tpl_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': '统一身份认证服务域名', 'verbose_name_plural': '统一身份认证服务域名'},
        ),
        migrations.AddField(
            model_name='domain',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='网站名称'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_mch_id',
            field=models.CharField(blank=True, default=None, help_text='微信商户号ID', max_length=32, null=True, verbose_name='微信商户号ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_mch_serial_no',
            field=models.CharField(blank=True, default=None, help_text='微信商户API证书序列号', max_length=64, null=True, verbose_name='微信商户API证书序列号'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(help_text='api域名:端口号 或 api域名', max_length=200, unique=True, verbose_name='名称'),
        ),
        migrations.CreateModel(
            name='ClientDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='api域名:端口号 或 api域名', max_length=200, unique=True, verbose_name='名称')),
                ('mobile', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='移动端域名')),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='网站名称')),
                ('logo', models.ImageField(blank=True, help_text='logo', null=True, upload_to='serve_logos', verbose_name='logo')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(help_text='统一身份认证服务域名', on_delete=django.db.models.deletion.CASCADE, related_name='client_domains', to='custom_servers.domain', verbose_name='统一身份认证服务域名')),
            ],
            options={
                'verbose_name': '客户端域名',
                'verbose_name_plural': '客户端域名',
            },
        ),
    ]
