# Generated by Django 4.2.20 on 2025-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0018_alter_domain_options_domain_title_domain_we_mch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdomain',
            name='name',
            field=models.CharField(help_text='前端域名:端口号 或 前端域名', max_length=200, unique=True, verbose_name='名称'),
        ),
    ]
