# Generated by Django 4.2.20 on 2026-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0020_domain_we_svc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdomain',
            name='name',
            field=models.CharField(help_text='前端域名(或IP)，不含端口号', max_length=200, unique=True, verbose_name='名称'),
        ),
    ]
