# Generated by Django 4.2.20 on 2026-04-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0022_remove_domain_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdomain',
            name='mobile',
            field=models.CharField(blank=True, default=None, help_text='例如：https://m.xxx.com:444/', max_length=200, null=True, verbose_name='移动端URL'),
        ),
    ]
