# Generated by Django 4.2.10 on 2024-06-06 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0015_tcpregistframe'),
        ('users', '0007_remove_projects_monitor_screen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='版本名称', max_length=100, null=True, verbose_name='版本名称')),
                ('version', models.CharField(help_text='version', max_length=20, verbose_name='版本号')),
                ('module', models.CharField(default='main', help_text='所属模块', max_length=60, verbose_name='所属模块')),
                ('use_https', models.BooleanField(default=False, help_text='是否使用https', verbose_name='是否使用https')),
                ('use_source_versions', models.BooleanField(default=False, help_text='是否指定待升级版本', verbose_name='是否指定待升级版本')),
                ('source_versions', models.JSONField(blank=True, help_text='待升级版本号列表', null=True, verbose_name='待升级版本号列表')),
                ('use_source_devices', models.BooleanField(default=False, help_text='是否指定待升级设备', verbose_name='是否指定待升级设备')),
                ('file_url', models.TextField(help_text='文件路径', verbose_name='文件路径')),
                ('desc', models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ota_cfgs', to='equipments.devicecategory', verbose_name='所属设备类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ota_cfgs', to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'OTA升级版本配置',
                'verbose_name_plural': 'OTA升级版本配置',
            },
        ),
        migrations.CreateModel(
            name='OtaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.device')),
                ('ota_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota_versions.otaconfig')),
            ],
            options={
                'verbose_name': 'OTA升级版本配置',
                'verbose_name_plural': 'OTA升级版本配置',
            },
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='source_devices',
            field=models.ManyToManyField(help_text='待升级设备', through='ota_versions.OtaDevice', to='equipments.device', verbose_name='待升级设备'),
        ),
    ]
