# Generated by Django 4.2.10 on 2024-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota_versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaconfig',
            name='file_md5',
            field=models.CharField(default='', help_text='文件md5', max_length=64, verbose_name='文件md5'),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='file_size',
            field=models.IntegerField(default=0, help_text='文件大小', verbose_name='文件大小'),
        ),
    ]
