# Generated by Django 4.2.20 on 2025-08-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0004_alter_sceneconfig_project'),
        ('users', '0013_alter_user_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0043_devicecategory_is_auto_create_cloudgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='操控面板名称', max_length=100, verbose_name='操控面板名称')),
                ('key', models.CharField(help_text='操控面板唯一标识：以"CK_"开头，如"CK_XXX"', max_length=64, unique=True, verbose_name='操控面板唯一标识')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_control_panels', to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '操控面板',
                'verbose_name_plural': '操控面板',
            },
        ),
        migrations.CreateModel(
            name='ControlPanelButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='按钮名称', max_length=100, verbose_name='按钮名称')),
                ('button_type', models.CharField(choices=[('command', '命令实例'), ('scene', '智能场景')], help_text='按钮类型', max_length=20, verbose_name='按钮类型')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('ordering', models.PositiveBigIntegerField(default=0, help_text='分组排序', verbose_name='分组排序')),
                ('command', models.ForeignKey(blank=True, help_text='命令实例', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.command', verbose_name='命令实例')),
                ('control_panel', models.ForeignKey(help_text='操控面板', on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='control_panels.controlpanel', verbose_name='操控面板')),
                ('scene', models.ForeignKey(blank=True, help_text='智能场景', null=True, on_delete=django.db.models.deletion.CASCADE, to='scenes.sceneconfig', verbose_name='智能场景')),
            ],
            options={
                'verbose_name': '操控面板按钮',
                'verbose_name_plural': '操控面板按钮',
            },
        ),
    ]
