# Generated by Django 4.2.20 on 2025-08-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0050_alter_fixedproduct_options'),
        ('control_panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanelbutton',
            name='device',
            field=models.ForeignKey(blank=True, help_text='设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.device', verbose_name='设备'),
        ),
    ]
