# Generated by Django 4.2.20 on 2025-09-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0054_alter_devicecategory_access_protocol'),
        ('control_panels', '0002_controlpanelbutton_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanelbutton',
            name='attr',
            field=models.ForeignKey(blank=True, help_text='设备属性', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.devicecategoryattrs', verbose_name='设备属性'),
        ),
        migrations.AddField(
            model_name='controlpanelbutton',
            name='password',
            field=models.CharField(blank=True, help_text='按钮口令', max_length=64, null=True, verbose_name='按钮口令'),
        ),
        migrations.AlterField(
            model_name='controlpanelbutton',
            name='button_type',
            field=models.CharField(choices=[('command', '命令实例'), ('scene', '智能场景'), ('attr', '设备属性')], help_text='按钮类型', max_length=20, verbose_name='按钮类型'),
        ),
    ]
