# Generated by Django 4.2.20 on 2025-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panels', '0003_controlpanelbutton_attr_controlpanelbutton_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanel',
            name='secret_key',
            field=models.CharField(blank=True, help_text='面板口令', max_length=64, null=True, verbose_name='面板口令'),
        ),
    ]
