# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '告警'), ('error', '故障')], default='info', help_text='等级', max_length=20, verbose_name='等级')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='是否已读', verbose_name='是否已读')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='消息描述', null=True, verbose_name='消息描述')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除', verbose_name='是否删除')),
                ('recipient', models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(blank=True, help_text='发起人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('source_content_type', models.ForeignKey(blank=True, help_text='消息类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_sources', to='contenttypes.contenttype', verbose_name='消息类型')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ('-timestamp',),
                'index_together': {('recipient', 'is_read')},
            },
        ),
    ]
