# Generated by Django 4.2.10 on 2024-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyrecord',
            name='content',
            field=models.FileField(blank=True, help_text='消息内容', null=True, upload_to='notice/%Y/%m/%d', verbose_name='消息内容'),
        ),
        migrations.AddField(
            model_name='notifyrecord',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本'), ('markdown', 'Markdown格式'), ('html', '网页格式')], default='text', help_text='消息类型', max_length=20, verbose_name='消息类型'),
        ),
        migrations.AddField(
            model_name='notifyrecord',
            name='title',
            field=models.CharField(default=None, help_text='消息标题', max_length=30, verbose_name='消息标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifyrecord',
            name='title_img',
            field=models.ImageField(blank=True, help_text='标题图片', null=True, upload_to='notice/%Y/%m/%d', verbose_name='标题图片'),
        ),
    ]
