# Generated by Django 4.2.10 on 2024-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notifyrecord_content_notifyrecord_msg_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyrecord',
            name='level',
        ),
        migrations.RemoveField(
            model_name='notifyrecord',
            name='source_content_type',
        ),
        migrations.RemoveField(
            model_name='notifyrecord',
            name='source_id',
        ),
        migrations.AddField(
            model_name='notifyrecord',
            name='msg_source',
            field=models.CharField(choices=[('site_msg', '站内信'), ('alarm', '告警通知')], default='msg', help_text='消息来源', max_length=20, verbose_name='消息来源'),
        ),
    ]
