# Generated by Django 4.2.10 on 2024-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_remove_notifyrecord_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyrecord',
            name='title_img',
        ),
        migrations.AlterField(
            model_name='notifyrecord',
            name='content',
            field=models.TextField(default=None, help_text='消息内容', verbose_name='消息内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifyrecord',
            name='msg_source',
            field=models.CharField(default='announcement', help_text='消息来源', max_length=20, verbose_name='消息来源'),
        ),
    ]
