# Generated by Django 4.2.10 on 2024-06-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_remove_notifyrecord_title_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyrecord',
            name='sender',
        ),
    ]
