# Generated by Django 4.2.13 on 2024-07-04 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0005_remove_notifyrecord_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyrecord',
            name='is_all',
            field=models.BooleanField(db_index=True, default=False, help_text='是否全站通告', verbose_name='是否全站通告'),
        ),
        migrations.AlterField(
            model_name='notifyrecord',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='接收人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
