# Generated by Django 4.2.13 on 2024-07-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_notifyrecord_is_all_alter_notifyrecord_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
