# Generated by Django 4.2.13 on 2024-07-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_alter_notifyrecord_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyrecord',
            name='is_deleted',
        ),
    ]
