# Generated by Django 4.2.16 on 2024-11-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0008_remove_notifyrecord_is_deleted'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='notifyrecord',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='notifyrecord',
            name='is_all',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='是否全站通告', verbose_name='是否全站通告'),
        ),
        migrations.RemoveField(
            model_name='notifyrecord',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notifyrecord',
            name='recipient',
        ),
        migrations.CreateModel(
            name='NotifyRecordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='是否已读', verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, help_text='读取时间', null=True, verbose_name='读取时间')),
                ('notify_record', models.ForeignKey(help_text='接收人', on_delete=django.db.models.deletion.CASCADE, related_name='notify_users', to='notice.notifyrecord', verbose_name='接收人')),
                ('recipient', models.ForeignKey(blank=True, help_text='接收人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '消息用户',
                'verbose_name_plural': '消息用户',
                'ordering': ('-id',),
                'index_together': {('recipient', 'is_read')},
            },
        ),
    ]
