# Generated by Django 4.2.16 on 2024-11-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_alter_notifyrecord_index_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyrecorduser',
            name='notify_record',
            field=models.ForeignKey(help_text='消息', on_delete=django.db.models.deletion.CASCADE, related_name='notify_users', to='notice.notifyrecord', verbose_name='消息'),
        ),
    ]
