# Generated by Django 4.2.17 on 2025-02-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_alter_notifyrecorduser_notify_record'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notifyrecorduser',
            new_name='notice_noti_recipie_49e00a_idx',
            old_fields=('recipient', 'is_read'),
        ),
    ]
