# Generated by Django 4.2.20 on 2025-08-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0011_rename_notifyrecorduser_recipient_is_read_notice_noti_recipie_49e00a_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyrecorduser',
            options={'ordering': ('-id',), 'verbose_name': '消息状态', 'verbose_name_plural': '消息状态'},
        ),
    ]
