# Generated by Django 4.2.20 on 2025-11-10 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_projectmembers_options'),
        ('notice', '0012_alter_notifyrecorduser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(choices=[('register_invite', '注册邀请'), ('common_verify', '验证码'), ('alarm_message', '告警通知'), ('alarm_restored', '告警恢复通知'), ('alarm_ongoing', '告警持续通知')], help_text='模板key', max_length=30, verbose_name='模板key')),
                ('mobile', models.CharField(help_text='手机号', max_length=20, verbose_name='手机号')),
                ('request_id', models.CharField(blank=True, help_text='请求标识', max_length=64, null=True, verbose_name='请求标识')),
                ('fee', models.PositiveSmallIntegerField(default=0, help_text='计费条数', verbose_name='计费条数')),
                ('params', models.JSONField(blank=True, help_text='短信参数', null=True, verbose_name='短信参数')),
                ('is_succeed', models.BooleanField(default=False, help_text='是否发送成功', verbose_name='是否发送成功')),
                ('error_msg', models.TextField(blank=True, help_text='失败原因', null=True, verbose_name='失败原因')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='发送时间', verbose_name='发送时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sms_records', to='users.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '短信记录',
                'verbose_name_plural': '短信记录',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['template_key', 'mobile', 'is_succeed'], name='notice_smsr_templat_bfc00e_idx')],
            },
        ),
    ]
