# Generated by Django 4.2.20 on 2025-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_smsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyrecord',
            name='title',
            field=models.CharField(help_text='消息标题', max_length=200, verbose_name='消息标题'),
        ),
    ]
